
#define XUA_Endpoint0_setVendorId     XUA_Endpoint0_setVendorId2
#define concatenateAndCopyStrings     concatenateAndCopyStrings2
#define XUA_Endpoint0_setStrTable     XUA_Endpoint0_setStrTable2
#define XUA_Endpoint0_setVendorStr     XUA_Endpoint0_setVendorStr2
#define XUA_Endpoint0_setProductStr     XUA_Endpoint0_setProductStr2
#define XUA_Endpoint0_setSerialStr     XUA_Endpoint0_setSerialStr2
#define XUA_Endpoint0_getVendorStr     XUA_Endpoint0_getVendorStr2
#define XUA_Endpoint0_getProductStr     XUA_Endpoint0_getProductStr2
#define XUA_Endpoint0_getSerialStr     XUA_Endpoint0_getSerialStr2
#define XUA_Endpoint0_setProductId     XUA_Endpoint0_setProductId2
#define XUA_Endpoint0_getVendorId     XUA_Endpoint0_getVendorId2
#define XUA_Endpoint0_getProductId     XUA_Endpoint0_getProductId2
#define XUA_Endpoint0_getBcdDevice     XUA_Endpoint0_getBcdDevice2
#define XUA_Endpoint0_setBcdDevice     XUA_Endpoint0_setBcdDevice2
#define XUA_Endpoint0_init     XUA_Endpoint0_init2
#define XUA_Endpoint0_loop     XUA_Endpoint0_loop2
#define XUA_Endpoint0     XUA_Endpoint02
#define g_strTable     g_strTable2
#define devDesc_Audio2     devDesc_Audio22
#define devDesc_Null     devDesc_Null2
#define devQualDesc_Audio2     devQualDesc_Audio22
#define devQualDesc_Null     devQualDesc_Null2
#define cfgDesc_Audio2     cfgDesc_Audio22
#define cfgDesc_Null     cfgDesc_Null2
#define DFU_mode_active     DFU_mode_active2
#define g_curStreamAlt_Out     g_curStreamAlt_Out2
#define g_curStreamAlt_In     g_curStreamAlt_In2
#define g_curUsbSpeed     g_curUsbSpeed2
#define g_vendor_str     g_vendor_str2
#define g_product_str     g_product_str2
#define g_serial_str     g_serial_str2
#define g_subSlot_Out_HS     g_subSlot_Out_HS2
#define g_subSlot_Out_FS     g_subSlot_Out_FS2
#define g_subSlot_In_HS     g_subSlot_In_HS2
#define g_subSlot_In_FS     g_subSlot_In_FS2
#define g_sampRes_Out_HS     g_sampRes_Out_HS2
#define g_sampRes_Out_FS     g_sampRes_Out_FS2
#define g_sampRes_In_HS     g_sampRes_In_HS2
#define g_sampRes_In_FS     g_sampRes_In_FS2
#define g_dataFormat_Out     g_dataFormat_Out2
#define g_dataFormat_In     g_dataFormat_In2
#define g_chanCount_In_HS     g_chanCount_In_HS2
#define ep0_out     ep0_out2
#define ep0_in     ep0_in2
#define volsOut     volsOut2
#define mutesOut     mutesOut2
#define volsIn     volsIn2
#define mutesIn     mutesIn2
#define XUA_Buffer_Decouple     XUA_Buffer_Decouple2
#define buffer_aud_ctl_chan     buffer_aud_ctl_chan2
#define aud_to_host_usb_ep     aud_to_host_usb_ep2
#define aud_from_host_usb_ep     aud_from_host_usb_ep2
#define inZeroBuff     inZeroBuff2
#define audioBuffIn     audioBuffIn2
#define outAudioBuff     outAudioBuff2
#define g_numUsbChan_In     g_numUsbChan_In2
#define handle_audio_request     handle_audio_request2
#define aud_to_host_fifo_end     aud_to_host_fifo_end2
#define aud_to_host_fifo_start     aud_to_host_fifo_start2
#define g_aud_from_host_wrptr     g_aud_from_host_wrptr2
#define aud_from_host_fifo_end     aud_from_host_fifo_end2
#define aud_from_host_fifo_start     aud_from_host_fifo_start2
#define g_maxPacketSize     g_maxPacketSize2
#define g_curSubSlot_In     g_curSubSlot_In2
#define g_curSubSlot_Out     g_curSubSlot_Out2
#define g_numUsbChan_Out     g_numUsbChan_Out2
#define unpackState     unpackState2
#define inUnderflow     inUnderflow2
#define outOverflow     outOverflow2
#define outUnderflow     outUnderflow2
#define g_aud_from_host_rdptr     g_aud_from_host_rdptr2
#define speedRem     speedRem2
#define packData     packData2
#define packState     packState2
#define unpackData     unpackData2
#define aud_data_remaining_to_device     aud_data_remaining_to_device2
#define totalSampsToWrite     totalSampsToWrite2
#define sampsToWrite     sampsToWrite2
#define multOut     multOut2
#define multOutPtr     multOutPtr2
#define multIn     multIn2
#define multInPtr     multInPtr2
#define g_aud_from_host_buffer     g_aud_from_host_buffer2
#define g_aud_to_host_flag     g_aud_to_host_flag2
#define g_aud_from_host_flag     g_aud_from_host_flag2
#define g_aud_from_host_info     g_aud_from_host_info2
#define g_freqChange_flag     g_freqChange_flag2
#define g_freqChange_sampFreq     g_freqChange_sampFreq2
#define g_formatChange_SubSlot     g_formatChange_SubSlot2
#define g_formatChange_DataFormat     g_formatChange_DataFormat2
#define g_formatChange_NumChans     g_formatChange_NumChans2
#define g_formatChange_SampRes     g_formatChange_SampRes2
#define g_aud_to_host_wrptr     g_aud_to_host_wrptr2
#define g_aud_to_host_dptr     g_aud_to_host_dptr2
#define g_aud_to_host_rdptr     g_aud_to_host_rdptr2
#define g_aud_to_host_fill_level     g_aud_to_host_fill_level2
#define aud_req_in_count     aud_req_in_count2
#define aud_req_out_count     aud_req_out_count2
#define XUA_Buffer_Ep     XUA_Buffer_Ep2
#define fb_clocks     fb_clocks2
#define feedbackValid     feedbackValid2
#define g_speed     g_speed2
#define XUA_Buffer     XUA_Buffer2
#define g_freqChange     g_freqChange2
#define masterClockFreq_ptr     masterClockFreq_ptr2
