#include "dual_xua_subs.h"

#define XUA_Endpoint0_setVendorId     XUA_Endpoint0_setVendorId2
#define concatenateAndCopyStrings     concatenateAndCopyStrings2
#define XUA_Endpoint0_setStrTable     XUA_Endpoint0_setStrTable2
#define XUA_Endpoint0_setVendorStr     XUA_Endpoint0_setVendorStr2
#define XUA_Endpoint0_setProductStr     XUA_Endpoint0_setProductStr2
#define XUA_Endpoint0_setSerialStr     XUA_Endpoint0_setSerialStr2
#define XUA_Endpoint0_getVendorStr     XUA_Endpoint0_getVendorStr2
#define XUA_Endpoint0_getProductStr     XUA_Endpoint0_getProductStr2
#define XUA_Endpoint0_getSerialStr     XUA_Endpoint0_getSerialStr2
#define XUA_Endpoint0_setProductId     XUA_Endpoint0_setProductId2
#define XUA_Endpoint0_getVendorId     XUA_Endpoint0_getVendorId2
#define XUA_Endpoint0_getProductId     XUA_Endpoint0_getProductId2
#define XUA_Endpoint0_getBcdDevice     XUA_Endpoint0_getBcdDevice2
#define XUA_Endpoint0_setBcdDevice     XUA_Endpoint0_setBcdDevice2
#define XUA_Endpoint0_init     XUA_Endpoint0_init2
#define XUA_Endpoint0_loop     XUA_Endpoint0_loop2
#define XUA_Endpoint0     XUA_Endpoint02
#define g_dataFormat_Out     g_dataFormat_Out2
#define g_dataFormat_In     g_dataFormat_In2
#define g_chanCount_In_HS     g_chanCount_In_HS2
#define ep0_out     ep0_out2
#define ep0_in     ep0_in2
#define mutesOut     mutesOut2
#define volsIn     volsIn2
#define mutesIn     mutesIn2
#define g_sampRes_Out_HS     g_sampRes_Out_HS2
#define g_sampRes_Out_FS     g_sampRes_Out_FS2
#define g_sampRes_In_HS     g_sampRes_In_HS2
#define g_product_str     g_product_str2
#define g_serial_str     g_serial_str2
#define g_subSlot_Out_HS     g_subSlot_Out_HS2
#define g_subSlot_Out_FS     g_subSlot_Out_FS2
#define g_subSlot_In_HS     g_subSlot_In_HS2
#define DFU_mode_active     DFU_mode_active2
#define g_curStreamAlt_Out     g_curStreamAlt_Out2
#define g_curStreamAlt_In     g_curStreamAlt_In2
#define g_curUsbSpeed     g_curUsbSpeed2
#define g_vendor_str     g_vendor_str2
#define devDesc_Audio2     devDesc_Audio22
#define devDesc_Null     devDesc_Null2
#define devQualDesc_Audio2     devQualDesc_Audio22
#define devQualDesc_Null     devQualDesc_Null2
#define cfgDesc_Audio2     cfgDesc_Audio22
#define devDesc_Audio2     devDesc_Audio22
#define devDesc_Null     devDesc_Null2
#define devQualDesc_Audio2     devQualDesc_Audio22
#define devQualDesc_Null     devQualDesc_Null2
#define cfgDesc_Audio2     cfgDesc_Audio22
#define g_subSlot_In_FS     g_subSlot_In_FS2
#define g_strTable     g_strTable2
#define devDesc_Null     devDesc_Null2
#define devQualDesc_Audio2     devQualDesc_Audio22
#define devQualDesc_Null     devQualDesc_Null2
#define cfgDesc_Audio2     cfgDesc_Audio22
#define cfgDesc_Null     cfgDesc_Null2
#define g_sampRes_In_FS     g_sampRes_In_FS2
#define volsOut     volsOut2

#include "../../../../lib_xua/src/core/endpoint0/xua_endpoint0.c"